### ISSUE TITLE
Linker error - CXX program compilation with Falaise

### ISSUE THREAD

**Issue by edbird** [SuperNEMO-DBD/brew#5]
I am trying to compile and link a c++ program.

Error specifics:

```
[100%] Linking CXX executable analysis
/home/ecb/snemo-sdk/lib/root/libtbb.so.2: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/home/ecb/snemo-sdk/lib/root/libtbb.so.2: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
collect2: error: ld returned 1 exit status
CMakeFiles/analysis.dir/build.make:116: recipe for target 'analysis' failed
make[2]: *** [analysis] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/analysis.dir/all' failed
make[1]: *** [CMakeFiles/analysis.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I have falaise installed and working.

This error occurs regardless of whether I call `eval $(~/snemo-sdk/bin/brew shellenv)` before running cmake.

My CXX file is compiled with cmake.

What further information is required?

I guess I can add my `CMakeLists.txt`

```
CMAKE_MINIMUM_REQUIRED(VERSION 3.7)

PROJECT(sfmlwav)

SET(CMAKE_CXX_STANDARD 14)
SET(CMAKE_BUILD_TYPE DEBUG)

SET(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} $ENV{ROOTSYS}/etc/cmake)

SET(SOURCE_FILES src/main.cpp)
SET(SOURCE_FILES_SOUND src/sound.cpp)
SET(SOURCE_FILES_ANALYSIS src/analysis.cpp)

ADD_EXECUTABLE(sfmlwav ${SOURCE_FILES})
ADD_EXECUTABLE(sound ${SOURCE_FILES_SOUND})
ADD_EXECUTABLE(analysis ${SOURCE_FILES_ANALYSIS})

FIND_PACKAGE(SFML REQUIRED audio graphics window system)
FIND_PACKAGE(ROOT REQUIRED)
LIST(APPEND CMAKE_PREFIX_PATH $ENV{ROOTSYS})
MESSAGE(STATUS "ROOT_FOUND=" ${ROOT_FOUND})
MESSAGE(STATUS "CMAKE_PREFIX_PATH=" ${CMAKE_PREFIX_PATH})
MESSAGE(STATUS "ROOT_INCLUDE_DIRS=" ${ROOT_INCLUDE_DIRS})
MESSAGE(STATUS "ROOT_LIBRARIES=" ${ROOT_LIBRARIES})

INCLUDE_DIRECTORIES(include ${SFML_INCLUDE_DIR} ${ROOT_INCLUDE_DIRS})

TARGET_LINK_LIBRARIES(sfmlwav ${SFML_LIBRARIES} fftw3)
TARGET_LINK_LIBRARIES(sound ${SFML_LIBRARIES})
TARGET_LINK_LIBRARIES(analysis ${SFML_LIBRARIES} ${ROOT_LIBRARIES} fftw3)
```

I am not super familiar with cmake, but this seems ok? You can ignore the exes; sfmlwav and sound as these compile and link ok.

**Comment by drbenmorgan** [comment]
Hi @edbird, I've moved to https://github.com/SuperNEMO-DBD/brew as this is not directly related to Falaise. 

What I *suspect* is happening is that CMake is picking up the system compiler rather than the brewed one (IIRC, Debian 9 is gcc 6, whereas SuperNEMO now uses gcc 7). You can check that by open the `CMakeCache.txt` file in the directory where you ran `cmake` and see if `CMAKE_CXX_COMPILER` points to `/usr/bin/gcc` or similar. If that's the case, you'll need to remove the directory where you built and start again. There are then two options:

1. _Recommended_: Use `brew snemo-shell` to start a dedicated shell session which should be set up such that `cmake` will find the brewed GCC and all needed packages (NB: not sure what SFML is, but if it's from the system, it should still be picked up)
2. Otherwise, the C/C++ compilers and CMake prefix path have to be passed explicitly:
   
 ```
  $ cmake -DCMAKE_C_COMPILER=$(brew --prefix)/bin/gcc-7 -DCMAKE_CXX_COMPILER=$(brew --prefix)/bin/g++-7 -DCMAKE_PREFIX_PATH=$(brew --prefix) /path/to/where/you/project/sourcedir/is
  ``` 

That should get things working, but note that *if* you use any C++ packages outside of the brewed set of packages, you *might* get further errors. The brewed system uses GCC 7 with C++11, whilst the system GCC (if it's GCC 6) will be C++14. Different C++ Standards *can* lead to ABI differences, though those between 11 and 14 *should* be minimal, but caveat emptor...

**Comment by edbird** [comment]
Thanks @drbenmorgan you guessed correctly... and indeed it works with snemo-shell - thanks

**Comment by drbenmorgan** [comment]
O.k., just closing this as you got it working!
